modLoader = "kotlinforforge"
loaderVersion = "[1,)"
license = "LGPL 3.0"
issueTrackerURL = "https://github.com/DeDiamondPro/Resourcify/issues"
showAsResourcePack = false

[[mods]]
modId = "resourcify"
version = "${version}"
displayName = "Resourcify"
authors = "DeDiamondPro"
description = "In-game resource pack, data pack and shader browser"
logoFile = "icon.png"
displayTest = "IGNORE_ALL_VERSION"

[[mixins]]
config = "forge.mixins.resourcify.json"